/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface MessageInterface extends utils.Interface {
  functions: {
    "addMessage(string)": FunctionFragment;
    "getMessageLength()": FunctionFragment;
    "selectMessage(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "addMessage" | "getMessageLength" | "selectMessage"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addMessage",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "selectMessage",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "addMessage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMessageLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selectMessage",
    data: BytesLike
  ): Result;

  events: {
    "AddMessage(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddMessage"): EventFragment;
}

export interface AddMessageEventObject {
  sender: string;
  message: string;
}
export type AddMessageEvent = TypedEvent<
  [string, string],
  AddMessageEventObject
>;

export type AddMessageEventFilter = TypedEventFilter<AddMessageEvent>;

export interface Message extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MessageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addMessage(
      message: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getMessageLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    selectMessage(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  addMessage(
    message: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getMessageLength(overrides?: CallOverrides): Promise<BigNumber>;

  selectMessage(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    addMessage(
      message: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getMessageLength(overrides?: CallOverrides): Promise<BigNumber>;

    selectMessage(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "AddMessage(address,string)"(
      sender?: null,
      message?: null
    ): AddMessageEventFilter;
    AddMessage(sender?: null, message?: null): AddMessageEventFilter;
  };

  estimateGas: {
    addMessage(
      message: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getMessageLength(overrides?: CallOverrides): Promise<BigNumber>;

    selectMessage(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addMessage(
      message: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getMessageLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    selectMessage(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
